version: 2
updates:
- package-ecosystem: cargo
  directory: /projects/sub_projects
  target-branch: dev
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /
  target-branch: dev
  schedule:
    interval: daily
