[package]
name = "yggdrasil-shared"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "AWSL Window Structure Language"
repository = "https://github.com/GalAster/awsl-rs"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
lsp-types = { version = "0.89", features = ["proposed"], optional = true }
url = { version = "2.0", optional = true }
thiserror = "1.0"
anyhow = "1.0"

[features]
default = ["lsp"]
lsp = ["lsp-types", "url"]