version = "Two"
edition = "2018"
max_width = 144

imports_granularity = "Crate"
use_small_heuristics = "Max"
control_brace_style = "ClosingNextLine"
normalize_comments = false
format_code_in_doc_comments = true
short_array_element_width_threshold = 9999999